steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ["build", "-t", "$_IMAGE_NAME:$_IMAGE_VERSION", "."]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ["push", "$_IMAGE_NAME:$_IMAGE_VERSION"]
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Prepare deploy'
  args:
  - 'prepare'
  - '--filename=$_K8S_YAML_PATH'
  - '--image=$_IMAGE_NAME:$_IMAGE_VERSION'
  - '--app=$_K8S_APP_NAME'
  - '--version=$_IMAGE_VERSION'
  - '--namespace=$_K8S_NAMESPACE'
  - '--output=$_OUTPUT_PATH'
  - '--annotation=gcb-build-id=$BUILD_ID'
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Apply deploy'
  args:
  - 'apply'
  - '--filename=$_OUTPUT_PATH/expanded'
  - '--namespace=$_K8S_NAMESPACE'
  - '--cluster=$_GKE_CLUSTER'
  - '--location=$_GKE_LOCATION'
images:
- '$_IMAGE_NAME:$_IMAGE_VERSION'
substitutions:
  _IMAGE_NAME: 'gcr.io/currypanman-experimental/github.com/currypanman/currypanman-experimental'
  _IMAGE_VERSION: $SHORT_SHA
  _GKE_CLUSTER: 'currypanman-experimental-cluster'
  _GKE_LOCATION: 'asia-northeast1'
  _K8S_APP_NAME: 'currypanman-experimental'
  _K8S_NAMESPACE: 'default'
  _K8S_YAML_PATH: 'kubernetes-deployment.yaml'
  _OUTPUT_PATH: 'output_path'
options:
  substitution_option: 'ALLOW_LOOSE'
tags: ['$_K8S_APP_NAME']
